const db = globalThis.__B44_DB__ || { auth:{ isAuthenticated: async()=>false, me: async()=>null }, entities:new Proxy({}, { get:()=>({ filter:async()=>[], get:async()=>null, create:async()=>({}), update:async()=>({}), delete:async()=>({}) }) }), integrations:{ Core:{ UploadFile:async()=>({ file_url:'' }) } } };

export const CATEGORIES = [
  {
    id: "main",
    label: "Main Portals",
    description: "Core class resources and projects",
  },
  {
    id: "other",
    label: "Other Sites",
    description: "More resources and projects",
  },
];

export const PORTALS = [
  {
    id: "finance",
    number: "01",
    title: "Financial Literacy",
    description: "A deep dive into financial literacy: tracking a full month of real budgeting, spending habits, and what I learned along the way.",
    tags: ["Budgeting", "Finance", "Project"],
    url: "https://finance.classresources.info/",
    domain: "finance.classresources.info",
    image: "https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=1200&auto=format&fit=crop&q=80",
    category: "main",
  },
  {
    id: "taxes",
    number: "02",
    title: "Taxes",
    description: "A streamlined tax resource portal with clear guidance, clean direction, and zero-friction entry into understanding taxation.",
    tags: ["Taxation", "Government", "Civic"],
    url: "https://taxes.classresources.info/",
    domain: "taxes.classresources.info",
    image: "https://images.unsplash.com/photo-1450101499163-c8848c66ca85?w=1200&auto=format&fit=crop&q=80",
    category: "main",
  },
  {
    id: "games",
    number: "03",
    title: "Financial Games",
    description: "Interactive financial simulation games that teach investment strategies, market dynamics, and money management through play.",
    tags: ["Games", "Simulation", "Finance"],
    url: "https://games.classresources.info/",
    domain: "games.classresources.info",
    image: "https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?w=1200&auto=format&fit=crop&q=80",
    category: "main",
  },
  {
    id: "harman",
    number: "04",
    title: "Harman's Budget",
    description: "A personal budgeting case study — follow Harman's real-world financial planning journey with detailed breakdowns and insights.",
    tags: ["Budget", "Case Study", "Personal Finance"],
    url: "http://harman.classresources.info/",
    domain: "harman.classresources.info",
    image: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=1200&auto=format&fit=crop&q=80",
    category: "main",
  },
  {
    id: "norway",
    number: "05",
    title: "Norway",
    description: "98% of Norway's energy comes from renewable sources. Explore how the country leads the world in clean, sustainable hydroelectric power.",
    tags: ["Renewable Energy", "Hydroelectric", "Sustainability"],
    url: "https://norway.classresources.info/",
    domain: "norway.classresources.info",
    image: "https://images.unsplash.com/photo-1531366936337-7c912a4589a7?w=1200&auto=format&fit=crop&q=80",
    category: "main",
  },
  {
    id: "watershed-game",
    number: "06",
    title: "Watershed Game",
    description: "Play interactive games designed to teach how watersheds function, making environmental science engaging and fun.",
    tags: ["Games", "Interactive", "Education"],
    url: "https://adventure.classresources.info/",
    domain: "adventure.classresources.info",
    image: "https://images.unsplash.com/photo-1501854140801-50d01698950b?w=1200&auto=format&fit=crop&q=80",
    category: "other",
  },
  {
    id: "watershed",
    number: "07",
    title: "Watershed",
    description: "Learn how watersheds work and follow our hands-on project where we built a mini watershed model to study water flow and runoff.",
    tags: ["Water Systems", "Ecology", "Project"],
    url: "https://watershed.classresources.info/",
    domain: "watershed.classresources.info",
    image: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=1200&auto=format&fit=crop&q=80",
    category: "other",
  },
  {
    id: "gphone",
    number: "08",
    title: "gPhone",
    description: "Our own software startup taking on the industry. gPhone is a homegrown platform built to rival the big players, built by us, for everyone.",
    tags: ["Startup", "Software", "Innovation"],
    url: "https://gphone.classresources.info/",
    domain: "gphone.classresources.info",
    image: "https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=1200&auto=format&fit=crop&q=80",
    category: "other",
  },
  {
    id: "guransh",
    number: "09",
    title: "Guransh's Site",
    description: "Guransh's personal resource portal — a hub for class projects, tools, and educational content.",
    tags: ["Personal", "Resources", "Portfolio"],
    url: "https://classresources.ca/",
    domain: "classresources.ca",
    image: "https://images.unsplash.com/photo-1488190211105-8b0e65b80b4e?w=1200&auto=format&fit=crop&q=80",
    category: "other",
  },
  {
    id: "jasraj",
    number: "10",
    title: "Jasraj's Site",
    description: "Jasraj's budget and finance portal — a personal project tracking spending, goals, and financial planning.",
    tags: ["Personal", "Budget", "Finance"],
    url: "https://jasraj-budget-pro.base44.app",
    domain: "classroomresources.xyz",
    image: "https://images.unsplash.com/photo-1579621970563-ebec7560ff3e?w=1200&auto=format&fit=crop&q=80",
    category: "other",
  },
];